/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Home' at '11/16/16 9:17 AM' with Gradle 2.14.1
 *
 * @author Home, @date 11/16/16 9:17 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
